services:
  ababil_web_dev:
    image: node:20
    container_name: ababil_web_dev
    working_dir: /app
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - web_network
    command: sh -c "npm install && npx prisma generate && npm run dev"

networks:
  web_network:
    external: true
