
services:
  ababil_web:
    image: bdcityapp/ababilfoundation:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ababil_web
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
